### ISSUE TITLE
How many rollouts does one step do?

### ISSUE THREAD

**Issue by DamienLopez1** [goktug97/estorch#1]
I have one step but it seems the number of rollouts are very large. Why is this?

**Comment by goktug97** [comment]
Evolution strategy algorithms have populations. In evolution strategy you estimate the gradient instead of calculating it using backpropagation. In the algorithms that are implemented here, the populations are created by adding noises to the network weights. When the said noises are gaussian, you can calculate the gradient, that optimizes the expected rewards, by multiplying the noise vectors with rewards. But when the population size is too low, the calculated gradient will have high variance. So lots of noise vectors are created from the same `mu` and `sigma` and run through the environment. That is why every step has to do `population_size` amounts of rollouts.

**Comment by DamienLopez1** [comment]
Thank you very much!
